# Schema for the configuration files of the User expire module.

user_expire.settings:
  type: config_object
  label: 'User expire settings'
  mapping:
    last_run:
      type: integer
      label: 'Last run'
    frequency:
      type: integer
      label: 'Frequency time'
    offset:
      type: integer
      label: 'Warning offset time'
